---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
spec:
  type: NodePort    
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 3000     
      targetPort: 3000
      nodePort: 30163
  
